version: '3.9'
services:
  backend:
    build: ./app
    network_mode: host
    privileged: true
    pid: host
    volumes:
      - /:/host
      - /var/run/docker.sock:/var/run/docker.sock
  frontend:
    build: ./frontend
    ports:
      - '8080:80'
